# Generated by Django 2.2.28 on 2023-06-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mini',
            name='sdg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
